### ISSUE TITLE
Bug in sketch.js

### ISSUE THREAD

**Issue by RR-121** [harshumakkar/Car-Racing#1]
Hi!

There is a bug in the game that I noticed while playing it. When you are on the form page and you enter your name and log in, the greeting is displayed. But, if you press the enter key (keyCode = 13) during the time when the greeting is displayed, the game jumps into its gameState 1, on all tabs.

I _guess_ this is causing the issue:

_sketch.js_
`function keyPressed() {
  if (keyCode === 13 && gameState !== 1 && passedFinish === false) {
    form.enter();
    console.log("hai");
    passedFinish = true;
  }
}`

Also, there is an additional sketch.js in your images folder.

**Comment by harshumakkar** [comment]
Thank you for letting me know. I will correct that, for sure.
